// TODO: Replace with file generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0PZJ6nfQFQxwStZLnTjD2V-RXFHPltnc',
    appId: '1:593791290330:web:65f53405578afa629fcee3',
    messagingSenderId: '593791290330',
    projectId: 'learn-firebase-for-flutt-6339b',
    authDomain: 'learn-firebase-for-flutt-6339b.firebaseapp.com',
    storageBucket: 'learn-firebase-for-flutt-6339b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVr_kDUK0yvI_QB3xdJVZW-lAFNhOreGQ',
    appId: '1:593791290330:android:00f10f3c63de6ddd9fcee3',
    messagingSenderId: '593791290330',
    projectId: 'learn-firebase-for-flutt-6339b',
    storageBucket: 'learn-firebase-for-flutt-6339b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfAeO7xlUNcGgmhB23jTzHjYP033kn3Wo',
    appId: '1:593791290330:ios:5bb51ad8a2e1826b9fcee3',
    messagingSenderId: '593791290330',
    projectId: 'learn-firebase-for-flutt-6339b',
    storageBucket: 'learn-firebase-for-flutt-6339b.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfAeO7xlUNcGgmhB23jTzHjYP033kn3Wo',
    appId: '1:593791290330:ios:5bb51ad8a2e1826b9fcee3',
    messagingSenderId: '593791290330',
    projectId: 'learn-firebase-for-flutt-6339b',
    storageBucket: 'learn-firebase-for-flutt-6339b.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

}